server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///mysql_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone:
      GMT+8
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.1.104:9300

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.chan.hotel.pojo
logging:
  level:
    com.chan: debug # com.chan包下的都会打印sql语句
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS